---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flux-app
  name: flux-deployment
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.flux-appl: glob:production-*
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flux-appl
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flux-appl
        app: flux-appl
    spec:
      containers:
      - image: 460811381319.dkr.ecr.ap-southeast-1.amazonaws.com/logback-demo:production-cbfd60d
        imagePullPolicy: IfNotPresent
        name: flux-appl
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: flux-app
  name: flux-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: flux-appl
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: flux-app
  name: flux-app-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: junjie-alb-group
spec:
  rules:
  - http:
      paths:
      - path: /demo/*
        backend:
          serviceName: flux-service
          servicePort: 8080
